@startuml Snake

class JuegoSnake {

}

class Jugador {
    
}

class Snake {
    +MoverIzquierda(Posicion)
    +MoverDerecha(Posicion)
    +MoverArriba(Posicion)
    +MoverAbajo(Posicion)
    +Comer(Manzana)
}

class Velocidad {
    +Aumentar(Puntuacion)
}

class Posicion {
    -posX
    -posY
}

class Posicion {


}

class Manzana {
    +Generar(Posicion)
    +Desaparecer(Snake)
}

class ObjetoDestruible {
    
}

class ObjetoIndestructible {
    
}

class Puntuacion {
    +IncrementarPuntuacion(Manzana)
}

class Mapa {
    
}

class Muro {
    
}

class Musica {
    +Reproducir()
    +Pausar()
}

class Partida {
    +Iniciar()
    +Terminar(Snake)
    +Reiniciar(Snake)
}

Partida *-- Mapa
Mapa *-- Muro
JuegoSnake "1" *-- "1" Jugador
Jugador "1" o-- "1" Snake
Snake *-- Posicion
Snake o-- Manzana
Snake *-- Velocidad
Velocidad "1" o-- "*" Puntuacion
Manzana --|> ObjetoDestruible
Manzana --|> Puntuacion
Muro --|> ObjetoIndestructible
JuegoSnake *-- Musica
JuegoSnake "1" *-- "*" Partida
Partida "1" *-- "*" Puntuacion

@enduml