@startuml Snake

class AssetCtrl{
    +~AssetCtrl()
    +AssetCtrl()
    -m_textures
    -m_fonts
    +AgregarTextura(int, string, bool)
    +AgregarFuente(int, string)
    +TomarTextura(int)
    +TomarFuente(int)

}

class GameOver {
    +~GameOver()
    +GameOver()
    -m_control
    -m_gameOverTitulo
    -m_salir
    -m_fondo
    -m_salirSelected
    -m_salirPressed
}

class GamePlay {
    +~GamePlay()
    +GamePlay()
    -m_control
    -m_snake
    -m_manzana
    -m_score
    -m_muro
    -m_mapa
    -m_musica
    -m_scoreText
    -m_snakeDireccion
    -m_tiempoTranscurrido
}

class GameSnake{
    +~GameSnake()
    +GameSnake()
    -m_control
    -timePerFrame
    +Correr()
}

class MenuPr {
    +~MenuPr()
    +MenuPr()
    -m_control
    -m_titulo
    -m_jugar
    -m_salir
    -m_fondo
    -m_jugarSelected
    -m_jugarPressed
    -m_salirSelected
    -m_salirPressed
}

class Snake{
    +~Snake()
    +Snake()
    -m_cuerpo
    -m_cabeza
    -m_cola
    -m_pos
    +Inicializar(Texture, Texture)
    +Mover(Vector2f, Texture, Texture)
    +Colisionar(Sprite)
    +Crecer(Vector2f, Texture)
    +AutoColisionar()
}

class State{
    +~State()
    +State()
    +Inicializar()
    +Actualizar()
    +Dibujar()
    +ProcesarEntrada(Time)
}

class StateCtrl{
    +~StateCtrl()
    +StateCtrl
    -m_stateStack
    -m_newState
    -m_add
    -m_replace
    -m_remove
    -m_removeAll
    +EliminarActual()
    +Agregar(State, bool)
    +EliminarTodo()
    +ProcesarCambioEstado()
    +ActivarVacio()
}

GameOver --|> State
GamePlay --|> State
MenuPr --|> State
GameSnake "1" *-- "1" GameOver
GameSnake "1" *-- "1" GamePlay
GameSnake "1" *-- "1" MenuPr
GameSnake o-- StateCtrl
GameOver "1" o-- "*" AssetCtrl
GamePlay *-- Snake
GamePlay "1" o-- "*" AssetCtrl
MenuPr "1" o-- "*" AssetCtrl

@enduml